package tc

import org.sireum._
import tc._
import org.sireum.Random.Impl.Xoshiro256

// Do not edit this file as it will be overwritten if SystemTestArtifactGen is rerun

object TempControl_Outputs_Container_Profile {

  def freshRandomLib: RandomLib = {
    return RandomLib(Random.Gen64Impl(Xoshiro256.create))
  }

  def getDefaultProfile: TempControl_Outputs_Container_Profile = {
    return TempControl_Outputs_Container_Profile (
      name = "Default TempControl_Outputs_Container_Profile Profile",
      numTestVectorGenRetries = 100,

      fanCmd = freshRandomLib,
      fanAck = freshRandomLib,
      fanIsOn = freshRandomLib,
      currentFanState = freshRandomLib,
      currentSetPoint = freshRandomLib
    )
  }
}

case class TempControl_Outputs_Container_Profile (
  var name: String,
  var numTestVectorGenRetries: Z,

  var fanCmd : RandomLib,
  var fanAck : RandomLib,
  var fanIsOn : RandomLib,
  var currentFanState : RandomLib,
  var currentSetPoint : RandomLib) extends org.sireum.$internal.MutableMarker {

  def next(): TempControl_Outputs_Container = {
    return TempControl_Outputs_Container (
      fanCmd.nextOptionTempControlMixedSeL4CAmKESFanCmdType(),
      fanAck.nextOptionTempControlMixedSeL4CAmKESFanAckType(),
      fanIsOn.nextB(),
      currentFanState.nextTempControlMixedSeL4CAmKESFanCmdType(),
      currentSetPoint.nextTempControlMixedSeL4CAmKESSetPoint()
    )
  }

  override def $clonable: Boolean = F

  override def $clonable_=(b: Boolean): org.sireum.$internal.MutableMarker = this

  override def $owned: Boolean = F

  override def $owned_=(b: Boolean): org.sireum.$internal.MutableMarker = this

  override def $clone: org.sireum.$internal.MutableMarker = this
}
