name: Linux

on:
  push:

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Tipe
        run: |
          ls -alig

          DISTRO=ive sh -c "$(curl -fsSL https://github.com/sireum/kekinian/releases/download/dev/install.cmd)"
          export SIREUM_HOME=$HOME/Applications/Sireum/
          export PATH=$SIREUM_HOME/bin:$PATH
          
          sireum
          
          ls -alig

          .ci/test.cmd
